# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NYTimesPopularTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NYTimesPopularTest

    pod 'Alamofire', '4.8.2'
    pod 'SwiftyJSON'
    pod 'NVActivityIndicatorView'
    pod 'Kingfisher'
    pod 'SkyFloatingLabelTextField', '~> 3.0'

  target 'NYTimesPopularTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NYTimesPopularTestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
